---
image: registry.gitlab.com/flotechnologies/devops/docker-tools@sha256:4442bf7c5959ab0b9428af9fb43bf6cc15f5b7f9f1b59f281adba9781633bb43

services:
  - docker:18.09-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://localhost:2375"
  CI_REGISTRY: "registry.gitlab.com"
  CI_REGISTRY_IMAGE: "${CI_REGISTRY}/flotechnologies/flo-public-gateway"

stages:
  - build
  - test
  - deploy-rc
  - verify-rc
  - deploy
  - verify

before_script:
  - |
    # TODO: this should be part of the compose image
    apk add --no-cache make bash jq gettext
    mkdir -pv "${HOME}/.docker/"
    echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
    docker login
    docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

Compile:
  stage: build
  except:
    - tags
  tags:
    - eks
  artifacts:
    paths:
      - logs/
      - node_modules/
      - dist
      - /root/.npm/_logs
    expire_in: 1 week
    # Cache modules in between jobs
  cache:
    untracked: true
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - .npm/
      - node_modules
  script:
    - make pull
    - make build
    - make audit
    - make push

Sanity:
  stage: test
  allow_failure: true
  artifacts:
    when: always
    paths:
      # Collect logs
      - build.log
      - /root/.npm/_logs
  dependencies:
    - Compile
  script:
    - make pull
    - make test | tee build.log
  tags:
    - eks

Dev:
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  stage: deploy
  dependencies:
    - Compile
  only:
    - dev
    - eks
    - /-ci$/i
  environment:
    name: eks
    url: https://flo-public-gateway.flocloud.co/api/v2/ping
  script:
    - make environment
    - make deploy
    - make deploy-status
  tags:
    - eks

ReleaseCandidate:
  variables:
    ENV: "rc"
    HELM_RELEASE_NAME: "flo-public-gateway-rc"
    K8S_NAMESPACE: "flo-public-gateway-rc"
    API_V1_URL_PROD: "http://flo-api.flo-api.svc.cluster.local:8000/api/v1"
    ACL_URL_PROD: "${API_V1_URL_PROD}/accesscontrol/refresh"
    AUTH_URL_PROD: "${API_V1_URL_PROD}/accesscontrol/authorize"
    DOCS_ENDPOINT_USER_PROD: "${DOCS_ENDPOINT_USER}"
    DYNAMO_TABLE_PREFIX_PROD: "prod_"
    EXTERNAL_DOCS_ENDPOINT_USER_PROD: "${EXTERNAL_DOCS_ENDPOINT_USER}"
    EXTERNAL_SERVICE_HTTP_TIMEOUT_MS_PROD: "10000"
    HEALTH_TEST_SERVICE_URL_PROD: "http://flo-device-manager.flo-device-manager.svc.cluster.local:8080"
    INFLUX_ANALYTICS_DB_PROD: "telemetry_analytics_prod"
    INFLUX_HOST_PROD: "mcfly-da662558.influxcloud.net"
    INFLUX_HOURLY_MEASUREMENT_PROD: "telemetry_hourly"
    INFLUX_PORT_PROD: "8086"
    INFLUX_SECOND_MEASUREMNT_PROD: '"twelve_weeks".telemetry_raw'
    INFLUX_TELEMETRY_DB_PROD: "telemetry_prod"
    INFLUX_USERNAME_PROD: "flo_api_prod"
    INSTANA_SERVICE_NAME: "flo-public-gateway-${ENV}"
    INTERNAL_FLO_MOEN_AUTH_URL_PROD: "http://flo-moen-auth.flo-moen-auth.svc.cluster.local:80"
    INTERNAL_DEVICE_SERVICE_BASE_URL_PROD: "http://flo-device-service.flo-device-service.svc.cluster.local:3000/v1"
    KAFKA_HOST_PROD: "kafka-cherry-broker-1.prod.flosecurecloud.com:9092,kafka-cherry-broker-2.prod.flosecurecloud.com:9092,kafka-cherry-broker-3.prod.flosecurecloud.com:9092"
    KAFKA_TIMEOUT_MS_PROD: "${KAFKA_TIMEOUT_MS}"
    POSTGRES_DATABASE_PROD: "${POSTGRES_DATABASE}"
    POSTGRES_HOST_PROD: "prod-rds.cutnsvmodttf.us-west-2.rds.amazonaws.com"
    POSTGRES_PORT_PROD: 5432
    POSTGRES_USER_PROD: "${POSTGRES_USER}"
    LOCALIZATION_API_URL_PROD: "http://flo-localization-service.flo-localization-service.svc.cluster.local:3000/v1"
    RESOURCE_EVENT_API_URL_PROD: "http://flo-resource-event.flo-resource-event.svc.cluster.local"
    NOTIFICATION_API_URL_PROD: "http://flo-notification-api.flo-notification-api.svc.cluster.local"
    PRESENCE_SERVICE_URL_PROD: "https://flo-core-service.flosecurecloud.com/presence"
    REDIS_HOST_PROD: "flo-api.k5ahfc.clustercfg.usw2.cache.amazonaws.com"
    TELEMETRY_TAGS_SERVICE_URL_PROD: "https://flo-telemetry-tags.flosecurecloud.com"
    SENSOR_METER_URL_PROD: "https://flo-puck-service.flosecurecloud.com"
    DEFAULT_NOTIFY_ACCOUNT_STATUS_EMAIL_PROD: "Suzanne.Street@moen.com"
    FLO_ENTERPRISE_SERVICE_URL_PROD: "http://flo-enterprise-service.flo-enterprise-service.svc.cluster.local:8080"
    CALLBACK_GATEWAY_HOST_PROD: "callback.meetflo.com"
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-2-17
  stage: deploy-rc
  allow_failure: true
  dependencies:
    - Compile
  only:
    - master
  environment:
    name: rc
    url: https://api-gw-rc.flosecurecloud.com/api/v2/ping
  script:
    - make environment-prod
    - make deploy
    - make deploy-status
  tags:
    - deploy-prod

K8sProd:
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
    ENV: prod
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  stage: deploy
  dependencies:
    - Compile
  only:
    - master
    - eks-prod
  environment:
    name: prod-eks
    url: https://api-gw.meetflo.com/api/v2/ping
  script:
    - make environment
    - make deploy
    - make deploy-status
  tags:
    - eks-prod

.RunscopeRC:
  variables:
    RS_ENV: "afe789b6-72d2-4270-a03e-44ea3562150d"
    RUNSCOPE_TRIGGER_URL: "https://api.runscope.com/radar/68e4a198-9132-4560-bb08-a2e746c8c3e6/trigger?runscope_environment=${RS_ENV}"
  stage: verify-rc
  allow_failure: true
  dependencies:
    - Compile
  only:
    - master
  environment:
    name: rc
    url: https://api-gw-rc.flosecurecloud.com/api/v2/ping
  script:
    - sleep 20
    - make runscope
  tags:
    - dev

RunscopeProd:
  variables:
    RS_ENV: "755b5795-c9d2-464f-9372-d2aaa106e5cc"
    RUNSCOPE_TRIGGER_URL: "https://api.runscope.com/radar/68e4a198-9132-4560-bb08-a2e746c8c3e6/trigger?runscope_environment=${RS_ENV}"
  stage: verify
  dependencies:
    - Compile
  only:
    - master
    - fix-runscope-pull
  environment:
    name: prod-eks
    url: https://api-gw.meetflo.com/api/v2/ping
  script:
    - sleep 20
    - make runscope
  tags:
    - eks-prod
