# This image is used as a build environment to run nodejs tools, like npm
FROM node:10-alpine

ARG NODE_ENV=development

RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    apk add --no-cache \
      bash \
      gcc \
      g++ \
      make \
      python \
      py-pip \
      git \
       && \
    pip install \
      awscli \
      awsebcli \
      direnv \
      pipenv \
    && \
    pip install PyYAML==3.12

WORKDIR /app
