FROM node:10-alpine

ARG NODE_ENV=development

RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    apk add --no-cache \
      bash \
      gcc \
      g++ \
      make \
      python \
      py-pip \
      git \
       && \
    pip install \
      direnv \
      pipenv

RUN mkdir -p /app
WORKDIR /app
COPY . /app

RUN npm install

CMD ["npm", "run", "watch-debug"]
