FROM node:12-alpine

ARG NODE_ENV=development

RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    apk add --no-cache \
      bash \
      gcc \
      g++ \
      make \
      git

RUN mkdir -p /app
WORKDIR /app
COPY . /app

RUN npm install

CMD ["npm", "run", "watch-debug"]
