# This image is used as a build environment to run nodejs tools, like npm
FROM node:10-alpine

ARG NODE_ENV=development

RUN echo https://sjc.edge.kernel.org/alpine/v3.9/main > /etc/apk/repositories
RUN echo https://sjc.edge.kernel.org/alpine/v3.9/community >> /etc/apk/repositories

RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    apk add --no-cache \
      bash \
      gcc \
      g++ \
      make \
      python \
      git

WORKDIR /app
