version: '3'

services:
  app:
    image: "flo-public-gateway:local"
    environment:
      NODE_ENV: "${NODE_ENV:-development}"
      DYNAMO_TABLE_PREFIX: "${DYNAMO_TABLE_PREFIX}"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
      API_VERSION: "2"
      AUTH_URL: "${AUTH_URL}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID-empty}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY-empty}"
      KAFKA_HOST: "${KAFKA_HOST}"
      KAFKA_TIMEOUT_MS: "${KAFKA_TIMEOUT_MS}"
    ports:
      - 3000:3000
      - 9229:9229

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1440