FROM registry.gitlab.com/flotechnologies/flo-public-gateway:build AS build

RUN mkdir -p /app
WORKDIR /app
COPY . /app
RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    apk add --no-cache \
      bash \
      gcc \
      g++ \
      make \
      python \
      py-pip \
      git 

RUN npm install

CMD ["npm", "start"]
