FROM node:18-alpine

ARG NODE_ENV=development

RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    apk add --no-cache \
      bash \
      gcc \
      g++ \
      make \
      git

RUN mkdir -p /app
WORKDIR /app
COPY . /app

RUN npm install -g npm@10.1.0
RUN npm ci --omit=optional

CMD ["npm", "run", "watch-debug"]
