FROM node:18-alpine

ARG COMMIT_SHA_ARG=blank
ENV COMMIT_SHA=$COMMIT_SHA_ARG

RUN mkdir -p /app
WORKDIR /app
COPY . /app

RUN npm install -g npm@10.1.0
RUN npm ci --omit=optional

RUN npm run build

CMD ["npm", "start"]
