FROM arm64v8/node:18-alpine

ARG NODE_ENV=development
ARG COMMIT_SHA_ARG=blank

ENV COMMIT_SHA=$COMMIT_SHA_ARG

RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    apk add --no-cache \
      bash \
      gcc \
      g++ \
      make \
      python3 \
      git

RUN npm install -g npm@10.1.0

WORKDIR /app
