---
version: '3'

services:
  app: &app
    image: "${CI_REGISTRY_IMAGE:-registry.gitlab.com/flotechnologies/flo-public-gateway}:latest"
    environment:
      NODE_ENV: "${NODE_ENV:-development}"
      DYNAMO_TABLE_PREFIX: "${DYNAMO_TABLE_PREFIX}"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
      API_VERSION: "${API_VERSION}"
      AUTH_URL: "${AUTH_URL}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID-empty}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY-empty}"
      KAFKA_HOST: "${KAFKA_HOST}"
      KAFKA_TIMEOUT_MS: "${KAFKA_TIMEOUT_MS}"
    ports:
      - 3000:3000
      - 9229:9229
    build:
      context: .
      dockerfile: Dockerfile.run
      args:
        COMMIT_SHA_ARG: "${COMMIT_SHA:-00000000}"

  # This is used to automatically tag the image with CI_PIPELINE_ID
  app-tag:
    entrypoint: "true"
    image: "${CI_REGISTRY_IMAGE:-registry.gitlab.com/flotechnologies/flo-public-gateway}:${CI_PIPELINE_ID:-latest}"
    ports: []
    <<: *app
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1440
