---
replicaCount: 9

environment: rc

image:
  repository: registry.gitlab.com/flotechnologies/flo-public-gateway
  tag:
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000
  livenessProbe:
    path: "/api/v2/ping"
    initialDelaySeconds: 35
    periodSeconds: 10
    timeoutSeconds: 1
  readinessProbe:
    path: "/api/v2/ping"
    initialDelaySeconds: 25
    periodSeconds: 5
    successThreshold: 2
    timeoutSeconds: 3

floApiUrl: "flo-api.flo-api.svc.cluster.local"

routingIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    production:
      - api.meetflo.com
      - api-gw.meetflo.com
      - flo-public-gateway.flosecurecloud.com
      - flo-public-gateway-prod.flosecurecloud.com
    development:
      - api-gw-dev.flocloud.co
      - flo-public-gateway-k8s.flocloud.co
    rc:
      - api-gw-rc.flosecurecloud.com
      - flo-public-gateway-rc.flosecurecloud.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

routingPaths:
  - name: /api/v2
  - name: /docs
  - name: /legacy
  - name: /swagger
  - name: /api/v1
    port: 8000
    servicePrefix: proxy-flo-api-


nodeSelector:
  kops.k8s.io/instancegroup: nodes

tolerations: []

affinity: {}

secrets:
  name: flocloud-public-gateway-secrets

resources:
  requests:
    cpu: 500m
    memory: 384Mi
  limits:
    cpu: "1500m"
    memory: 768Mi
