---
replicaCount: 13

environment: rc

image:
  repository: registry.gitlab.com/flotechnologies/flo-public-gateway
  tag:
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000
  livenessProbe:
    path: "/api/v2/ping"
    initialDelaySeconds: 35
    periodSeconds: 10
    timeoutSeconds: 1
  readinessProbe:
    path: "/api/v2/ping"
    initialDelaySeconds: 25
    periodSeconds: 5
    successThreshold: 2
    timeoutSeconds: 3

floApiUrl: "flo-api.flo-api.svc.cluster.local"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: 200,404
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
  path: "/*"
  hosts: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


floApiProxyConfig: |
  server {
          listen       80;
          server_name  _;
          location / {
              add_header 'Access-Control-Allow-Origin' '*';
              add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
              #
              # Custom headers and headers various browsers *should* be OK with but aren't
              #
              add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
              proxy_pass   flo-api.flo-api.svc.cluster.local;
          }

  }

publicGatewayProxyConfig: |
  server {
            listen       80;
            server_name  _;
            location / {
                proxy_pass   http://flo-public-gateway.flo-public-gateway.svc.cluster.local:3000;
            }

    }

routingPaths:
  - name: /api/v2
  - name: /docs
  - name: /legacy
  - name: /swagger
  - name: /api/v1
    port: 8000
    servicePrefix: proxy-flo-api-


tolerations: []

affinity: {}

secrets:
  name: flocloud-public-gateway-secrets

resources:
  requests:
    cpu: 500m
    memory: 384Mi
  # limits:
  #   cpu: 3
  #   memory: 2Gi
