---
replicaCount: 3

environment: dev

image:
  repository: registry.gitlab.com/flotechnologies/flo-public-gateway
  tag:
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

v1ProxyService:
  floApiV1Hostname: api-dev.flocloud.co

routingIngress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: internal-ingress.flocloud.co 
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx
  hosts:
    - api.meetflo.com
    - api-gw-dev.flocloud.co
    - flo-public-gateway-k8s.flocloud.co
    - flo-public-gateway.flosecurecloud.com
    - flo-public-gateway-prod.flosecurecloud.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

internalIngress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
  host: internal-ingress.flocloud.co

resources: {}

nodeSelector:
  kops.k8s.io/instancegroup: nodes

tolerations: []

affinity: {}

secrets:
  name: flocloud-public-gateway-secrets

resources:
  requests:
    cpu: 128m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
