---
replicaCount: 9

environment: rc

image:
  repository: registry.gitlab.com/flotechnologies/flo-public-gateway
  tag:
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000
  livenessProbe:
    path: "/api/v2/ping"
    initialDelaySeconds: 35
    periodSeconds: 10
    timeoutSeconds: 1
  readinessProbe:
    path: "/api/v2/ping"
    initialDelaySeconds: 25
    periodSeconds: 5
    successThreshold: 2
    timeoutSeconds: 3

v1ProxyService:
  production: "not-for-public-use-api-gw.meetflo.com"
  development: "api-dev.flocloud.co"
  rc: "not-for-public-use-api-gw.meetflo.com"

routingIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  hosts:
    production:
      - api.meetflo.com
      - api-gw.meetflo.com
      - flo-public-gateway.flosecurecloud.com
      - flo-public-gateway-prod.flosecurecloud.com
    development:
      - api-gw-dev.flocloud.co
      - flo-public-gateway-k8s.flocloud.co
    rc:
      - api-gw-rc.flosecurecloud.com
      - flo-public-gateway-rc.flosecurecloud.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

routingPaths:
  - name: /api/v2
    servicePrefix: proxy-k8s
  - name: /docs
    servicePrefix: proxy-k8s
  - name: /legacy
    servicePrefix: proxy-k8s
  - name: /swagger
    servicePrefix: proxy-k8s
  - name: /api/v1
    servicePrefix: proxy-eb

internalIngress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx

internalIngressHosts:
  production: "internal-ingress.flosecurecloud.com"
  development: "internal-ingress.flocloud.co"
  rc: "internal-ingress-rc.flosecurecloud.com"

nodeSelector:
  kops.k8s.io/instancegroup: nodes

tolerations: []

affinity: {}

secrets:
  name: flocloud-public-gateway-secrets

resources:
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: "3"
    memory: 1024Mi
