apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "flo-public-gateway.fullname" . }}-hpa
spec:
{{- if eq .Values.environment "prod" }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ add .Values.replicaCount 2 }}
{{- else  }}
  minReplicas: 2
  maxReplicas: 4
{{- end }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "flo-public-gateway.fullname" . }}
