---
kind: Service
apiVersion: v1
metadata:
  name: proxy-eb-{{ include "flo-public-gateway.fullname" . }}

spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ExternalName
  externalName: flo-public-gateway.flocloud.co