---
kind: Service
apiVersion: v1
metadata:
  name: proxy-eb-{{ include "flo-public-gateway.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443 
  type: ExternalName
  externalName: {{ .Values.v1ProxyService.floApiV1Hostname }}

---
kind: Service
apiVersion: v1
metadata:
  name: proxy-k8s-{{ include "flo-public-gateway.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: ExternalName
  externalName: {{ .Values.internalIngress.host }}
