---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "flo-public-gateway.proxy-to-flo-api-name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  type: ExternalName
  externalName: {{ .Values.floApiUrl | quote }}

