---
kind: Service
apiVersion: v1
metadata:
  name: proxy-eb-{{ include "flo-public-gateway.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443 
  type: ExternalName
  externalName: api-dev.flocloud.co 

---
kind: Service
apiVersion: v1
metadata:
  name: proxy-k8s-{{ include "flo-public-gateway.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host flo-public-gateway-k8s.flocloud.co;
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: ExternalName
  externalName: flo-public-gateway-k8s.flocloud.co
