---
kind: Service
apiVersion: v1
metadata:
  name: proxy-eb-{{ include "flo-public-gateway.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  type: ExternalName
{{- if eq .Values.environment "production" }}
  externalName: {{ .Values.v1ProxyService.production }}
{{- else if eq .Values.environment "rc" }}
  externalName: {{ .Values.v1ProxyService.rc }}
{{- else  }}
  externalName: {{ .Values.v1ProxyService.development }}
{{- end }}

---
kind: Service
apiVersion: v1
metadata:
  name: proxy-k8s-{{ include "flo-public-gateway.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  type: ExternalName
{{- if eq .Values.environment "production" }}
  externalName: {{ .Values.internalIngressHosts.production }}
{{- else if eq .Values.environment "rc" }}
  externalName: {{ .Values.internalIngressHosts.rc }}
{{- else  }}
  externalName: {{ .Values.internalIngressHosts.development }}
{{- end }}
