apiVersion: v1
kind: Secret
metadata:
  name: flocloud-public-gateway-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "flo-public-gateway.name" . }}
    chart: {{ template "flo-public-gateway.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.datas }}
    {{ $key }}: {{ default "" $value | replace ":" "" | b64enc | quote }}
  {{- end }}