{{- $fullName := include "flo-public-gateway.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flo-public-gateway.fullname" . }}-v1-proxy
  labels:
    app: {{ include "flo-public-gateway.name" . }}-v1-proxy
    app.kubernetes.io/name: {{ include "flo-public-gateway.name" . }}-v1-proxy
    app.kubernetes.io/environment: {{ .Values.secrets.datas.ENVIRONMENT }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "flo-public-gateway.chart" . }}
spec:
{{ if eq .Values.environment "prod" }}
  replicas: {{ .Values.replicaCount }}
{{ else  }}
  replicas: 1
{{ end }}
  selector:
    matchLabels:
      app: {{ include "flo-public-gateway.name" . }}-v1-proxy
      app.kubernetes.io/name: {{ include "flo-public-gateway.name" . }}-v1-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ include "flo-public-gateway.name" . }}-v1-proxy
        app.kubernetes.io/name: {{ include "flo-public-gateway.name" . }}-v1-proxy
        app.kubernetes.io/environment: {{ .Values.secrets.datas.ENVIRONMENT }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "flo-public-gateway.chart" . }}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      volumes:
        - name: nginx-config
          configMap:
            name: {{ $fullName }}-nginx-config
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: extra-vhost.conf
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
